wordlist: wordlist.c
	gcc wordlist.c -o wordlist

clean:
	rm -f wordlist
	
run: 
	./wordlist -b hello friendly world
	./wordlist -r hello friendly world
	./wordlist -rr hello friendly world
	./wordlist -br hello friendly world
	./wordlist -bbb hello friendly world
	./wordlist -rrr hello friendly world
